version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "npm"
    groups:
      aksel-dependencies:
        patterns:
          - "@navikt/ds-*"
          - "@navikt/aksel-*"
      react-dependencies:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "github-actions"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "[docker]"
