apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-mock-alt-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: "{{image}}"
  port: 3008
  ingresses:
   - "https://digisos.ekstern.dev.nav.no/sosialhjelp/mock-alt"
  liveness:
    path: /sosialhjelp/mock-alt/internal/isAlive
    initialDelay: 5
  readiness:
    path: /sosialhjelp/mock-alt/internal/isReady
    initialDelay: 5
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 1m
      memory: 32Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 70
  filesFrom:
    - emptyDir:
        medium: Disk
      mountPath: /var/cache/nginx/
    - emptyDir:
        medium: Disk
      mountPath: /var/run/
