apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-mock-alt-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 3000
  ingresses:
   - "https://sosialhjelp-mock-alt-mock.ekstern.dev.nav.no/sosialhjelp/mock-alt"
  liveness:
    path: /sosialhjelp/mock-alt/api/internal/isAlive
    initialDelay: 5
  readiness:
    path: /sosialhjelp/mock-alt/api/internal/isReady
    initialDelay: 5
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 1m
      memory: 32Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 70
  accessPolicy:
    outbound:
      external:
        - host: digisos.ekstern.dev.nav.no
  env:
    - name: HOST_ADDRESS
      value: "https://digisos.ekstern.dev.nav.no/"
    - name: COOKIE_DOMAIN
      value: "digisos.ekstern.dev.nav.no"
